name: Android Build
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r25c

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib run lime rebuild hxcpp

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -final -D officialBuild

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: Psych Engine Android
          path: export/release/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
