name: Android Build

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '25.2.9519653'
          cmake-version: '3.22.1'
          accept-android-licenses: true

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: '4.3.4'
          neko-version: '2.3.0'

      - name: Install Dependencies
        run: |
          mkdir -p ~/haxelib
          haxelib setup ~/haxelib
          haxelib install lime --quiet
          haxelib install hxcpp --quiet
          haxelib install extension-androidtools --quiet
          haxelib run lime rebuild hxcpp

      - name: Configure Android Tools
        run: |
          haxelib run lime setup android --force
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653

      - name: Build Android APK
        run: |
          haxelib run lime clean android
          haxelib run lime build android -final -D officialBuild -v
          mkdir -p artifacts
          cp export/release/android/bin/app/build/outputs/apk/release/*.apk artifacts/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngine-Android
          path: artifacts/*.apk
          retention-days: 7
